a = (input('Digite algo: '))
print('É alfanumérico? ', a.isalnum())
print('É alfabético? ', a.isalpha())
print('É um dígito? ', a.isdigit())
print('É minúsculo? ', a.islower())
print('É decimal? ', a.isdecimal())
print('É numérico?', a.isnumeric())
print('É maiúsculo?', a.isupper())
